#:schema node_modules/wrangler/config-schema.json
name = "dress-up"
main = ".open-next/worker.js"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

# Run `wrangler d1 create dress-up` and replace database_id below.
[[d1_databases]]
binding = "DB"
database_name = "dress-up"
database_id = "c5f3ab2e-fcca-4a7a-926e-05f4afcd2ed6"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "dress-up-images"

[ai]
binding = "AI"
